name: projeto_leituramiga
description: Interfaces gráficas do LeiturAmiga.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_animate: ^4.3.0
  flutter_lints: ^2.0.0
  auto_route: ^8.2.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  date_picker_plus: ^3.0.2
  image_picker: ^1.1.2
  table_calendar: ^3.1.2
  shared_preferences: ^2.3.2
  mask_text_input_formatter: ^2.5.0
  dio: ^5.7.0
  connectivity_plus: ^2.3.0
  flutter_image_compress: ^2.3.0
  image: ^4.3.0

  leituramiga:
    path: ../leituramiga

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/svg/academico/
    - assets/svg/exclusao/
    - assets/svg/seta/
    - assets/svg/tema/
    - assets/svg/usuario/
    - assets/svg/menu/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonte/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonte/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonte/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonte/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonte/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonte/Montserrat/Montserrat-Medium.ttf

    - family: MontserratAlternates
      fonts:
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Black.ttf
          weight: 900
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Regular.ttf
          weight: 500
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-Thin.ttf
          weight: 100
        - asset: assets/fonte/Montserrat_Alternates/MontserratAlternates-ThinItalic.ttf
          weight: 100
          style: italic